# Generated by Django 5.2.17 on 2026-08-12 21:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('role', models.CharField(choices=[('student', 'دانشجو'), ('company', 'نماینده شرکت'), ('admin', 'مدیر سیستم')], default='student', max_length=10, verbose_name='نقش')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر')),
                ('full_name', models.CharField(default='', max_length=255, verbose_name='نام و نام خانوادگی')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'db_table': 'accounts_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام شرکت')),
                ('industry', models.CharField(blank=True, max_length=255, null=True, verbose_name='حوزه فعالیت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وب\u200cسایت')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس شرکت')),
                ('license_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره مجوز/ثبت')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='لوگو')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت اعتبار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل شرکت',
                'verbose_name_plural': 'پروفایل\u200cهای شرکت\u200cها',
                'db_table': 'accounts_company',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(blank=True, max_length=255, null=True, verbose_name='دانشگاه')),
                ('major', models.CharField(blank=True, max_length=255, null=True, verbose_name='رشته تحصیلی')),
                ('grade', models.CharField(blank=True, max_length=100, null=True, verbose_name='مقطع تحصیلی')),
                ('student_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره دانشجویی')),
                ('gpa', models.CharField(blank=True, max_length=10, null=True, verbose_name='معدل')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='مهارت\u200cها')),
                ('interests', models.TextField(blank=True, null=True, verbose_name='علاقه\u200cمندی\u200cها')),
                ('about', models.TextField(blank=True, null=True, verbose_name='درباره من')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='فایل رزومه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل دانشجو',
                'verbose_name_plural': 'پروفایل\u200cهای دانشجویان',
                'db_table': 'accounts_student',
            },
        ),
    ]
