# Generated by Django 5.2.17 on 2026-08-12 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان موقعیت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='ظرفیت پذیرش')),
                ('required_skills', models.JSONField(blank=True, default=list, verbose_name='مهارت\u200cهای مورد نیاز')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر')),
                ('major', models.CharField(blank=True, max_length=255, null=True, verbose_name='رشته تحصیلی')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('conditions', models.TextField(blank=True, null=True, verbose_name='شرایط کاری')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('closed', 'بسته شده')], default='active', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='accounts.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'فرصت کارآموزی',
                'verbose_name_plural': 'فرصت\u200cهای کارآموزی',
                'db_table': 'internships_internship',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('cover_letter', models.TextField(blank=True, null=True, verbose_name='نامه درخواست')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.student', verbose_name='دانشجو')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='internships.internship', verbose_name='فرصت کارآموزی')),
            ],
            options={
                'verbose_name': 'درخواست کارآموزی',
                'verbose_name_plural': 'درخواست\u200cهای کارآموزی',
                'db_table': 'internships_application',
                'ordering': ['-created_at'],
                'unique_together': {('internship', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=50, unique=True, verbose_name='شماره سریال')),
                ('university', models.CharField(blank=True, max_length=255, verbose_name='نام دانشگاه')),
                ('student_name', models.CharField(max_length=255, verbose_name='نام دانشجو')),
                ('student_number', models.CharField(blank=True, max_length=50, verbose_name='شماره دانشجویی')),
                ('student_major', models.CharField(blank=True, max_length=255, verbose_name='رشته تحصیلی')),
                ('student_grade', models.CharField(blank=True, max_length=100, verbose_name='مقطع تحصیلی')),
                ('company_name', models.CharField(max_length=255, verbose_name='نام شرکت')),
                ('internship_title', models.CharField(max_length=255, verbose_name='عنوان کارآموزی')),
                ('start_date', models.CharField(blank=True, max_length=20, verbose_name='تاریخ شروع')),
                ('end_date', models.CharField(blank=True, max_length=20, verbose_name='تاریخ پایان')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='letter', to='internships.application', verbose_name='درخواست')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='internships.internship', verbose_name='فرصت کارآموزی')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='accounts.student', verbose_name='دانشجو')),
            ],
            options={
                'verbose_name': 'معرفی\u200cنامه',
                'verbose_name_plural': 'معرفی\u200cنامه\u200cها',
                'db_table': 'internships_letter',
                'ordering': ['-issued_at'],
            },
        ),
    ]
